apiVersion: aws.platformref.crossplane.io/v1alpha1
kind: CwpCluster
metadata:
  name: my-cluster-claim-1
spec:
  id: cluster-claim-1
  namespace: cluster-1-ns
  parameters:
    region: eu-west-1

  writeConnectionSecretToRef:
    name: cluster-1-secret
    #namespace: cluster-1-ns